#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SERVIFLEX")]
	public partial class LinQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public LinQDataContext() : 
				base(global::AccesoDatos.Properties.Settings.Default.SERVIFLEXConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LinQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarDatosUsuario")]
		public int SP_ActualizarDatosUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESION_ID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> sESION_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROVINCIA_ID", DbType="Int")] System.Nullable<int> pROVINCIA_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CANTON_ID", DbType="Int")] System.Nullable<int> cANTON_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="VarChar(20)")] string tELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="Text")] string dIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sESION_ID, pROVINCIA_ID, cANTON_ID, tELEFONO, dIRECCION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(7)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarFotoPerfil")]
		public int SP_ActualizarFotoPerfil([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESION_ID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> sESION_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FOTO_PERFIL", DbType="VarChar(255)")] string fOTO_PERFIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sESION_ID, fOTO_PERFIL, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ActualizarServicio")]
		public int SP_ActualizarServicio([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SERVICIO_ID", DbType="Int")] System.Nullable<int> sERVICIO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="Text")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRECIO", DbType="Int")] System.Nullable<int> pRECIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DISPONIBILIDAD", DbType="Text")] string dISPONIBILIDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sERVICIO_ID, dESCRIPCION, pRECIO, dISPONIBILIDAD, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_CompletarPerfil")]
		public int SP_CompletarPerfil([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESION_ID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> sESION_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PROVINCIA_ID", DbType="Int")] System.Nullable<int> pROVINCIA_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CANTON_ID", DbType="Int")] System.Nullable<int> cANTON_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FOTO_PERFIL", DbType="VarChar(255)")] string fOTO_PERFIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="VarChar(20)")] string tELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="Text")] string dIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sESION_ID, pROVINCIA_ID, cANTON_ID, fOTO_PERFIL, tELEFONO, dIRECCION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarConversacion")]
		public int SP_EliminarConversacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONVERSACION_ID", DbType="Int")] System.Nullable<int> cONVERSACION_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cONVERSACION_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarImagen")]
		public int SP_EliminarImagen([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IMAGEN_ID", DbType="Int")] System.Nullable<int> iMAGEN_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iMAGEN_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarMensaje")]
		public int SP_EliminarMensaje([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MENSAJE_ID", DbType="Int")] System.Nullable<int> mENSAJE_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mENSAJE_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarResena")]
		public int SP_EliminarResena([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResenaID", DbType="Int")] System.Nullable<int> resenaID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), resenaID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_EliminarServicio")]
		public int SP_EliminarServicio([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SERVICIO_ID", DbType="Int")] System.Nullable<int> sERVICIO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sERVICIO_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarConversacion")]
		public int SP_InsertarConversacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESION_ID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> sESION_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO2_ID", DbType="Int")] System.Nullable<int> uSUARIO2_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SERVICIO_ID", DbType="Int")] System.Nullable<int> sERVICIO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sESION_ID, uSUARIO2_ID, sERVICIO_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarImagen")]
		public int SP_InsertarImagen([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SERVICIO_ID", DbType="Int")] System.Nullable<int> sERVICIO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RUTA_IMAGEN", DbType="VarChar(255)")] string rUTA_IMAGEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sERVICIO_ID, rUTA_IMAGEN, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarMensaje")]
		public int SP_InsertarMensaje([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESION_ID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> sESION_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONVERSACION_ID", DbType="Int")] System.Nullable<int> cONVERSACION_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTENIDO", DbType="Text")] string cONTENIDO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sESION_ID, cONVERSACION_ID, cONTENIDO, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarResena")]
		public int SP_InsertarResena([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SesionID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> sesionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServicioID", DbType="Int")] System.Nullable<int> servicioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Calificacion", DbType="Int")] System.Nullable<int> calificacion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comentario", DbType="Text")] string comentario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sesionID, servicioID, calificacion, comentario, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(5)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(6)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarServicio")]
		public int SP_InsertarServicio([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESION_ID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> sESION_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CATEGORIA_ID", DbType="Int")] System.Nullable<int> cATEGORIA_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TITULO", DbType="VarChar(255)")] string tITULO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DESCRIPCION", DbType="Text")] string dESCRIPCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PRECIO", DbType="Int")] System.Nullable<int> pRECIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DISPONIBILIDAD", DbType="Text")] string dISPONIBILIDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sESION_ID, cATEGORIA_ID, tITULO, dESCRIPCION, pRECIO, dISPONIBILIDAD, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(6)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(7)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(8)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarSubCategoriaServicio")]
		public int SP_InsertarSubCategoriaServicio([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SERVICIO_ID", DbType="Int")] System.Nullable<int> sERVICIO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUB_CATEGORIA_ID", DbType="Int")] System.Nullable<int> sUB_CATEGORIA_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sERVICIO_ID, sUB_CATEGORIA_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_InsertarUsuario")]
		public int SP_InsertarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(100)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO1", DbType="VarChar(100)")] string aPELLIDO1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO2", DbType="VarChar(100)")] string aPELLIDO2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_NACIMIENTO", DbType="Date")] System.Nullable<System.DateTime> fECHA_NACIMIENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="VarChar(255)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SALT", DbType="VarChar(255)")] string sALT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA", DbType="VarChar(255)")] string cONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VERIFICACION", DbType="Int")] System.Nullable<int> vERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE, aPELLIDO1, aPELLIDO2, fECHA_NACIMIENTO, cORREO, sALT, cONTRASENA, vERIFICACION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(8)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(9)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(10)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarCantones")]
		public ISingleResult<SP_ListarCantonesResult> SP_ListarCantones([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(0)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_ListarCantonesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarCategorias")]
		public ISingleResult<SP_ListarCategoriasResult> SP_ListarCategorias([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(0)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_ListarCategoriasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarConversacionesPorUsuario")]
		public ISingleResult<SP_ListarConversacionesPorUsuarioResult> SP_ListarConversacionesPorUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESION_ID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> sESION_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sESION_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_ListarConversacionesPorUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarImagenesPorServicio")]
		public ISingleResult<SP_ListarImagenesPorServicioResult> SP_ListarImagenesPorServicio([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SERVICIO_ID", DbType="Int")] System.Nullable<int> sERVICIO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sERVICIO_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_ListarImagenesPorServicioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarMensajesPorConversacion")]
		public ISingleResult<SP_ListarMensajesPorConversacionResult> SP_ListarMensajesPorConversacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ConversacionID", DbType="Int")] System.Nullable<int> conversacionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), conversacionID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_ListarMensajesPorConversacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarProvincias")]
		public ISingleResult<SP_ListarProvinciasResult> SP_ListarProvincias([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(0)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_ListarProvinciasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarResenasPorServicio")]
		public ISingleResult<SP_ListarResenasPorServicioResult> SP_ListarResenasPorServicio([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ServicioID", DbType="Int")] System.Nullable<int> servicioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), servicioID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_ListarResenasPorServicioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarResenasPorUsuario")]
		public ISingleResult<SP_ListarResenasPorUsuarioResult> SP_ListarResenasPorUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SesionID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> sesionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sesionID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_ListarResenasPorUsuarioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarServicios")]
		public ISingleResult<SP_ListarServiciosResult> SP_ListarServicios([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(0)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_ListarServiciosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarServiciosPorCategoriaId")]
		public ISingleResult<SP_ListarServiciosPorCategoriaIdResult> SP_ListarServiciosPorCategoriaId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CATEGORIA_ID", DbType="Int")] System.Nullable<int> cATEGORIA_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cATEGORIA_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_ListarServiciosPorCategoriaIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarServiciosPorSubCategoriaId")]
		public ISingleResult<SP_ListarServiciosPorSubCategoriaIdResult> SP_ListarServiciosPorSubCategoriaId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SUB_CATEGORIA_ID", DbType="Int")] System.Nullable<int> sUB_CATEGORIA_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sUB_CATEGORIA_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_ListarServiciosPorSubCategoriaIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarServiciosPorUsuarioId")]
		public ISingleResult<SP_ListarServiciosPorUsuarioIdResult> SP_ListarServiciosPorUsuarioId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO_ID", DbType="Int")] System.Nullable<int> uSUARIO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_ListarServiciosPorUsuarioIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ListarSubCategorias")]
		public ISingleResult<SP_ListarSubCategoriasResult> SP_ListarSubCategorias([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(0)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(2)));
			return ((ISingleResult<SP_ListarSubCategoriasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LOGIN_USUARIO")]
		public int SP_LOGIN_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CORREO", DbType="VarChar(255)")] string cORREO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CONTRASENA", DbType="VarChar(255)")] string cONTRASENA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESION_ID", DbType="UniqueIdentifier")] ref System.Nullable<System.Guid> sESION_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cORREO, cONTRASENA, sESION_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			sESION_ID = ((System.Nullable<System.Guid>)(result.GetParameterValue(2)));
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(4)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(5)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ObtenerServicio")]
		public ISingleResult<SP_ObtenerServicioResult> SP_ObtenerServicio([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SERVICIO_ID", DbType="Int")] System.Nullable<int> sERVICIO_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sERVICIO_ID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_ObtenerServicioResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_Verificacion")]
		public int SP_Verificacion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SESION_ID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> sESION_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VERIFICACION", DbType="Int")] System.Nullable<int> vERIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sESION_ID, vERIFICACION, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(3)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(4)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ObtenerUsuario")]
		public ISingleResult<SP_ObtenerUsuarioResult> SP_ObtenerUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDRETURN", DbType="Int")] ref System.Nullable<int> iDRETURN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORID", DbType="Int")] ref System.Nullable<int> eRRORID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ERRORDESCRIPCION", DbType="NVarChar(MAX)")] ref string eRRORDESCRIPCION)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioID, iDRETURN, eRRORID, eRRORDESCRIPCION);
			iDRETURN = ((System.Nullable<int>)(result.GetParameterValue(1)));
			eRRORID = ((System.Nullable<int>)(result.GetParameterValue(2)));
			eRRORDESCRIPCION = ((string)(result.GetParameterValue(3)));
			return ((ISingleResult<SP_ObtenerUsuarioResult>)(result.ReturnValue));
		}
	}
	
	public partial class SP_ListarCantonesResult
	{
		
		private int _CANTON_ID;
		
		private string _NOMBRE;
		
		private string _PROVINCIA;
		
		public SP_ListarCantonesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTON_ID", DbType="Int NOT NULL")]
		public int CANTON_ID
		{
			get
			{
				return this._CANTON_ID;
			}
			set
			{
				if ((this._CANTON_ID != value))
				{
					this._CANTON_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVINCIA", DbType="VarChar(255)")]
		public string PROVINCIA
		{
			get
			{
				return this._PROVINCIA;
			}
			set
			{
				if ((this._PROVINCIA != value))
				{
					this._PROVINCIA = value;
				}
			}
		}
	}
	
	public partial class SP_ListarCategoriasResult
	{
		
		private int _CATEGORIA_ID;
		
		private string _NOMBRE;
		
		private System.Nullable<System.DateTime> _CREATED_AT;
		
		private System.Nullable<System.DateTime> _UPDATED_AT;
		
		public SP_ListarCategoriasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA_ID", DbType="Int NOT NULL")]
		public int CATEGORIA_ID
		{
			get
			{
				return this._CATEGORIA_ID;
			}
			set
			{
				if ((this._CATEGORIA_ID != value))
				{
					this._CATEGORIA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_AT
		{
			get
			{
				return this._CREATED_AT;
			}
			set
			{
				if ((this._CREATED_AT != value))
				{
					this._CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_AT
		{
			get
			{
				return this._UPDATED_AT;
			}
			set
			{
				if ((this._UPDATED_AT != value))
				{
					this._UPDATED_AT = value;
				}
			}
		}
	}
	
	public partial class SP_ListarConversacionesPorUsuarioResult
	{
		
		private int _CONVERSACION_ID;
		
		private System.Nullable<int> _USUARIO1_ID;
		
		private string _USUARIO1_NOMBRE;
		
		private string _USUARIO1_APELLIDO1;
		
		private string _USUARIO1_APELLIDO2;
		
		private System.Nullable<int> _USUARIO2_ID;
		
		private string _USUARIO2_NOMBRE;
		
		private string _USUARIO2_APELLIDO1;
		
		private string _USUARIO2_APELLIDO2;
		
		private System.Nullable<int> _SERVICIO_ID;
		
		private string _SERVICIO_TITULO;
		
		private System.Nullable<System.DateTime> _CREATED_AT;
		
		private System.Nullable<System.DateTime> _UPDATED_AT;
		
		public SP_ListarConversacionesPorUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONVERSACION_ID", DbType="Int NOT NULL")]
		public int CONVERSACION_ID
		{
			get
			{
				return this._CONVERSACION_ID;
			}
			set
			{
				if ((this._CONVERSACION_ID != value))
				{
					this._CONVERSACION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO1_ID", DbType="Int")]
		public System.Nullable<int> USUARIO1_ID
		{
			get
			{
				return this._USUARIO1_ID;
			}
			set
			{
				if ((this._USUARIO1_ID != value))
				{
					this._USUARIO1_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO1_NOMBRE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string USUARIO1_NOMBRE
		{
			get
			{
				return this._USUARIO1_NOMBRE;
			}
			set
			{
				if ((this._USUARIO1_NOMBRE != value))
				{
					this._USUARIO1_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO1_APELLIDO1", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string USUARIO1_APELLIDO1
		{
			get
			{
				return this._USUARIO1_APELLIDO1;
			}
			set
			{
				if ((this._USUARIO1_APELLIDO1 != value))
				{
					this._USUARIO1_APELLIDO1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO1_APELLIDO2", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string USUARIO1_APELLIDO2
		{
			get
			{
				return this._USUARIO1_APELLIDO2;
			}
			set
			{
				if ((this._USUARIO1_APELLIDO2 != value))
				{
					this._USUARIO1_APELLIDO2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO2_ID", DbType="Int")]
		public System.Nullable<int> USUARIO2_ID
		{
			get
			{
				return this._USUARIO2_ID;
			}
			set
			{
				if ((this._USUARIO2_ID != value))
				{
					this._USUARIO2_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO2_NOMBRE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string USUARIO2_NOMBRE
		{
			get
			{
				return this._USUARIO2_NOMBRE;
			}
			set
			{
				if ((this._USUARIO2_NOMBRE != value))
				{
					this._USUARIO2_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO2_APELLIDO1", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string USUARIO2_APELLIDO1
		{
			get
			{
				return this._USUARIO2_APELLIDO1;
			}
			set
			{
				if ((this._USUARIO2_APELLIDO1 != value))
				{
					this._USUARIO2_APELLIDO1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO2_APELLIDO2", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string USUARIO2_APELLIDO2
		{
			get
			{
				return this._USUARIO2_APELLIDO2;
			}
			set
			{
				if ((this._USUARIO2_APELLIDO2 != value))
				{
					this._USUARIO2_APELLIDO2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICIO_ID", DbType="Int")]
		public System.Nullable<int> SERVICIO_ID
		{
			get
			{
				return this._SERVICIO_ID;
			}
			set
			{
				if ((this._SERVICIO_ID != value))
				{
					this._SERVICIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICIO_TITULO", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string SERVICIO_TITULO
		{
			get
			{
				return this._SERVICIO_TITULO;
			}
			set
			{
				if ((this._SERVICIO_TITULO != value))
				{
					this._SERVICIO_TITULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_AT
		{
			get
			{
				return this._CREATED_AT;
			}
			set
			{
				if ((this._CREATED_AT != value))
				{
					this._CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_AT
		{
			get
			{
				return this._UPDATED_AT;
			}
			set
			{
				if ((this._UPDATED_AT != value))
				{
					this._UPDATED_AT = value;
				}
			}
		}
	}
	
	public partial class SP_ListarImagenesPorServicioResult
	{
		
		private int _IMAGEN_ID;
		
		private string _RUTA_IMAGEN;
		
		private System.Nullable<System.DateTime> _CREATED_AT;
		
		private System.Nullable<System.DateTime> _UPDATED_AT;
		
		public SP_ListarImagenesPorServicioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IMAGEN_ID", DbType="Int NOT NULL")]
		public int IMAGEN_ID
		{
			get
			{
				return this._IMAGEN_ID;
			}
			set
			{
				if ((this._IMAGEN_ID != value))
				{
					this._IMAGEN_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RUTA_IMAGEN", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string RUTA_IMAGEN
		{
			get
			{
				return this._RUTA_IMAGEN;
			}
			set
			{
				if ((this._RUTA_IMAGEN != value))
				{
					this._RUTA_IMAGEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_AT
		{
			get
			{
				return this._CREATED_AT;
			}
			set
			{
				if ((this._CREATED_AT != value))
				{
					this._CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_AT
		{
			get
			{
				return this._UPDATED_AT;
			}
			set
			{
				if ((this._UPDATED_AT != value))
				{
					this._UPDATED_AT = value;
				}
			}
		}
	}
	
	public partial class SP_ListarMensajesPorConversacionResult
	{
		
		private int _MENSAJE_ID;
		
		private System.Nullable<int> _CONVERSACION_ID;
		
		private System.Nullable<int> _USUARIO_ID;
		
		private string _NOMBRE_USUARIO;
		
		private string _CONTENIDO;
		
		private System.Nullable<System.DateTime> _CREATED_AT;
		
		public SP_ListarMensajesPorConversacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENSAJE_ID", DbType="Int NOT NULL")]
		public int MENSAJE_ID
		{
			get
			{
				return this._MENSAJE_ID;
			}
			set
			{
				if ((this._MENSAJE_ID != value))
				{
					this._MENSAJE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONVERSACION_ID", DbType="Int")]
		public System.Nullable<int> CONVERSACION_ID
		{
			get
			{
				return this._CONVERSACION_ID;
			}
			set
			{
				if ((this._CONVERSACION_ID != value))
				{
					this._CONVERSACION_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ID", DbType="Int")]
		public System.Nullable<int> USUARIO_ID
		{
			get
			{
				return this._USUARIO_ID;
			}
			set
			{
				if ((this._USUARIO_ID != value))
				{
					this._USUARIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_USUARIO", DbType="VarChar(201) NOT NULL", CanBeNull=false)]
		public string NOMBRE_USUARIO
		{
			get
			{
				return this._NOMBRE_USUARIO;
			}
			set
			{
				if ((this._NOMBRE_USUARIO != value))
				{
					this._NOMBRE_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONTENIDO", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string CONTENIDO
		{
			get
			{
				return this._CONTENIDO;
			}
			set
			{
				if ((this._CONTENIDO != value))
				{
					this._CONTENIDO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_AT
		{
			get
			{
				return this._CREATED_AT;
			}
			set
			{
				if ((this._CREATED_AT != value))
				{
					this._CREATED_AT = value;
				}
			}
		}
	}
	
	public partial class SP_ListarProvinciasResult
	{
		
		private int _PROVINCIA_ID;
		
		private string _NOMBRE;
		
		private System.Nullable<System.DateTime> _CREATED_AT;
		
		private System.Nullable<System.DateTime> _UPDATED_AT;
		
		public SP_ListarProvinciasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVINCIA_ID", DbType="Int NOT NULL")]
		public int PROVINCIA_ID
		{
			get
			{
				return this._PROVINCIA_ID;
			}
			set
			{
				if ((this._PROVINCIA_ID != value))
				{
					this._PROVINCIA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_AT
		{
			get
			{
				return this._CREATED_AT;
			}
			set
			{
				if ((this._CREATED_AT != value))
				{
					this._CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_AT
		{
			get
			{
				return this._UPDATED_AT;
			}
			set
			{
				if ((this._UPDATED_AT != value))
				{
					this._UPDATED_AT = value;
				}
			}
		}
	}
	
	public partial class SP_ListarResenasPorServicioResult
	{
		
		private int _RESENA_ID;
		
		private System.Nullable<int> _USUARIO_ID;
		
		private string _NOMBRE_USUARIO;
		
		private int _CALIFICACION;
		
		private string _COMENTARIO;
		
		private System.Nullable<System.DateTime> _CREATED_AT;
		
		public SP_ListarResenasPorServicioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESENA_ID", DbType="Int NOT NULL")]
		public int RESENA_ID
		{
			get
			{
				return this._RESENA_ID;
			}
			set
			{
				if ((this._RESENA_ID != value))
				{
					this._RESENA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ID", DbType="Int")]
		public System.Nullable<int> USUARIO_ID
		{
			get
			{
				return this._USUARIO_ID;
			}
			set
			{
				if ((this._USUARIO_ID != value))
				{
					this._USUARIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_USUARIO", DbType="VarChar(201) NOT NULL", CanBeNull=false)]
		public string NOMBRE_USUARIO
		{
			get
			{
				return this._NOMBRE_USUARIO;
			}
			set
			{
				if ((this._NOMBRE_USUARIO != value))
				{
					this._NOMBRE_USUARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALIFICACION", DbType="Int NOT NULL")]
		public int CALIFICACION
		{
			get
			{
				return this._CALIFICACION;
			}
			set
			{
				if ((this._CALIFICACION != value))
				{
					this._CALIFICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMENTARIO", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string COMENTARIO
		{
			get
			{
				return this._COMENTARIO;
			}
			set
			{
				if ((this._COMENTARIO != value))
				{
					this._COMENTARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_AT
		{
			get
			{
				return this._CREATED_AT;
			}
			set
			{
				if ((this._CREATED_AT != value))
				{
					this._CREATED_AT = value;
				}
			}
		}
	}
	
	public partial class SP_ListarResenasPorUsuarioResult
	{
		
		private int _RESENA_ID;
		
		private System.Nullable<int> _SERVICIO_ID;
		
		private string _SERVICIO_TITULO;
		
		private int _CALIFICACION;
		
		private string _COMENTARIO;
		
		private System.Nullable<System.DateTime> _CREATED_AT;
		
		private System.Nullable<System.DateTime> _UPDATED_AT;
		
		public SP_ListarResenasPorUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESENA_ID", DbType="Int NOT NULL")]
		public int RESENA_ID
		{
			get
			{
				return this._RESENA_ID;
			}
			set
			{
				if ((this._RESENA_ID != value))
				{
					this._RESENA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICIO_ID", DbType="Int")]
		public System.Nullable<int> SERVICIO_ID
		{
			get
			{
				return this._SERVICIO_ID;
			}
			set
			{
				if ((this._SERVICIO_ID != value))
				{
					this._SERVICIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICIO_TITULO", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string SERVICIO_TITULO
		{
			get
			{
				return this._SERVICIO_TITULO;
			}
			set
			{
				if ((this._SERVICIO_TITULO != value))
				{
					this._SERVICIO_TITULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALIFICACION", DbType="Int NOT NULL")]
		public int CALIFICACION
		{
			get
			{
				return this._CALIFICACION;
			}
			set
			{
				if ((this._CALIFICACION != value))
				{
					this._CALIFICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMENTARIO", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string COMENTARIO
		{
			get
			{
				return this._COMENTARIO;
			}
			set
			{
				if ((this._COMENTARIO != value))
				{
					this._COMENTARIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_AT
		{
			get
			{
				return this._CREATED_AT;
			}
			set
			{
				if ((this._CREATED_AT != value))
				{
					this._CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_AT
		{
			get
			{
				return this._UPDATED_AT;
			}
			set
			{
				if ((this._UPDATED_AT != value))
				{
					this._UPDATED_AT = value;
				}
			}
		}
	}
	
	public partial class SP_ListarServiciosResult
	{
		
		private int _SERVICIO_ID;
		
		private System.Nullable<int> _USUARIO_ID;
		
		private string _USUARIO_NOMBRE;
		
		private string _USUARIO_APELLIDO1;
		
		private string _USUARIO_APELLIDO2;
		
		private System.Nullable<int> _CATEGORIA_ID;
		
		private string _CATEGORIA_NOMBRE;
		
		private string _TITULO;
		
		private string _DESCRIPCION;
		
		private int _PRECIO;
		
		private string _DISPONIBILIDAD;
		
		private System.Nullable<System.DateTime> _CREATED_AT;
		
		private System.Nullable<System.DateTime> _UPDATED_AT;
		
		private System.Nullable<int> _SUB_CATE_SERV_ID;
		
		private System.Nullable<int> _SUB_CATEGORIA_ID;
		
		private string _SUB_CATEGORIA_NOMBRE;
		
		public SP_ListarServiciosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICIO_ID", DbType="Int NOT NULL")]
		public int SERVICIO_ID
		{
			get
			{
				return this._SERVICIO_ID;
			}
			set
			{
				if ((this._SERVICIO_ID != value))
				{
					this._SERVICIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ID", DbType="Int")]
		public System.Nullable<int> USUARIO_ID
		{
			get
			{
				return this._USUARIO_ID;
			}
			set
			{
				if ((this._USUARIO_ID != value))
				{
					this._USUARIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_NOMBRE", DbType="VarChar(100)")]
		public string USUARIO_NOMBRE
		{
			get
			{
				return this._USUARIO_NOMBRE;
			}
			set
			{
				if ((this._USUARIO_NOMBRE != value))
				{
					this._USUARIO_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_APELLIDO1", DbType="VarChar(100)")]
		public string USUARIO_APELLIDO1
		{
			get
			{
				return this._USUARIO_APELLIDO1;
			}
			set
			{
				if ((this._USUARIO_APELLIDO1 != value))
				{
					this._USUARIO_APELLIDO1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_APELLIDO2", DbType="VarChar(100)")]
		public string USUARIO_APELLIDO2
		{
			get
			{
				return this._USUARIO_APELLIDO2;
			}
			set
			{
				if ((this._USUARIO_APELLIDO2 != value))
				{
					this._USUARIO_APELLIDO2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA_ID", DbType="Int")]
		public System.Nullable<int> CATEGORIA_ID
		{
			get
			{
				return this._CATEGORIA_ID;
			}
			set
			{
				if ((this._CATEGORIA_ID != value))
				{
					this._CATEGORIA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA_NOMBRE", DbType="VarChar(255)")]
		public string CATEGORIA_NOMBRE
		{
			get
			{
				return this._CATEGORIA_NOMBRE;
			}
			set
			{
				if ((this._CATEGORIA_NOMBRE != value))
				{
					this._CATEGORIA_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITULO", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string TITULO
		{
			get
			{
				return this._TITULO;
			}
			set
			{
				if ((this._TITULO != value))
				{
					this._TITULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Int NOT NULL")]
		public int PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISPONIBILIDAD", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DISPONIBILIDAD
		{
			get
			{
				return this._DISPONIBILIDAD;
			}
			set
			{
				if ((this._DISPONIBILIDAD != value))
				{
					this._DISPONIBILIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_AT
		{
			get
			{
				return this._CREATED_AT;
			}
			set
			{
				if ((this._CREATED_AT != value))
				{
					this._CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_AT
		{
			get
			{
				return this._UPDATED_AT;
			}
			set
			{
				if ((this._UPDATED_AT != value))
				{
					this._UPDATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATE_SERV_ID", DbType="Int")]
		public System.Nullable<int> SUB_CATE_SERV_ID
		{
			get
			{
				return this._SUB_CATE_SERV_ID;
			}
			set
			{
				if ((this._SUB_CATE_SERV_ID != value))
				{
					this._SUB_CATE_SERV_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATEGORIA_ID", DbType="Int")]
		public System.Nullable<int> SUB_CATEGORIA_ID
		{
			get
			{
				return this._SUB_CATEGORIA_ID;
			}
			set
			{
				if ((this._SUB_CATEGORIA_ID != value))
				{
					this._SUB_CATEGORIA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATEGORIA_NOMBRE", DbType="VarChar(255)")]
		public string SUB_CATEGORIA_NOMBRE
		{
			get
			{
				return this._SUB_CATEGORIA_NOMBRE;
			}
			set
			{
				if ((this._SUB_CATEGORIA_NOMBRE != value))
				{
					this._SUB_CATEGORIA_NOMBRE = value;
				}
			}
		}
	}
	
	public partial class SP_ListarServiciosPorCategoriaIdResult
	{
		
		private int _SERVICIO_ID;
		
		private System.Nullable<int> _USUARIO_ID;
		
		private string _USUARIO_NOMBRE;
		
		private string _USUARIO_APELLIDO1;
		
		private string _USUARIO_APELLIDO2;
		
		private System.Nullable<int> _CATEGORIA_ID;
		
		private string _CATEGORIA_NOMBRE;
		
		private string _TITULO;
		
		private string _DESCRIPCION;
		
		private int _PRECIO;
		
		private string _DISPONIBILIDAD;
		
		private System.Nullable<System.DateTime> _CREATED_AT;
		
		private System.Nullable<System.DateTime> _UPDATED_AT;
		
		private System.Nullable<int> _SUB_CATE_SERV_ID;
		
		private System.Nullable<int> _SUB_CATEGORIA_ID;
		
		private string _SUB_CATEGORIA_NOMBRE;
		
		public SP_ListarServiciosPorCategoriaIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICIO_ID", DbType="Int NOT NULL")]
		public int SERVICIO_ID
		{
			get
			{
				return this._SERVICIO_ID;
			}
			set
			{
				if ((this._SERVICIO_ID != value))
				{
					this._SERVICIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ID", DbType="Int")]
		public System.Nullable<int> USUARIO_ID
		{
			get
			{
				return this._USUARIO_ID;
			}
			set
			{
				if ((this._USUARIO_ID != value))
				{
					this._USUARIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_NOMBRE", DbType="VarChar(100)")]
		public string USUARIO_NOMBRE
		{
			get
			{
				return this._USUARIO_NOMBRE;
			}
			set
			{
				if ((this._USUARIO_NOMBRE != value))
				{
					this._USUARIO_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_APELLIDO1", DbType="VarChar(100)")]
		public string USUARIO_APELLIDO1
		{
			get
			{
				return this._USUARIO_APELLIDO1;
			}
			set
			{
				if ((this._USUARIO_APELLIDO1 != value))
				{
					this._USUARIO_APELLIDO1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_APELLIDO2", DbType="VarChar(100)")]
		public string USUARIO_APELLIDO2
		{
			get
			{
				return this._USUARIO_APELLIDO2;
			}
			set
			{
				if ((this._USUARIO_APELLIDO2 != value))
				{
					this._USUARIO_APELLIDO2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA_ID", DbType="Int")]
		public System.Nullable<int> CATEGORIA_ID
		{
			get
			{
				return this._CATEGORIA_ID;
			}
			set
			{
				if ((this._CATEGORIA_ID != value))
				{
					this._CATEGORIA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA_NOMBRE", DbType="VarChar(255)")]
		public string CATEGORIA_NOMBRE
		{
			get
			{
				return this._CATEGORIA_NOMBRE;
			}
			set
			{
				if ((this._CATEGORIA_NOMBRE != value))
				{
					this._CATEGORIA_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITULO", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string TITULO
		{
			get
			{
				return this._TITULO;
			}
			set
			{
				if ((this._TITULO != value))
				{
					this._TITULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Int NOT NULL")]
		public int PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISPONIBILIDAD", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DISPONIBILIDAD
		{
			get
			{
				return this._DISPONIBILIDAD;
			}
			set
			{
				if ((this._DISPONIBILIDAD != value))
				{
					this._DISPONIBILIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_AT
		{
			get
			{
				return this._CREATED_AT;
			}
			set
			{
				if ((this._CREATED_AT != value))
				{
					this._CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_AT
		{
			get
			{
				return this._UPDATED_AT;
			}
			set
			{
				if ((this._UPDATED_AT != value))
				{
					this._UPDATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATE_SERV_ID", DbType="Int")]
		public System.Nullable<int> SUB_CATE_SERV_ID
		{
			get
			{
				return this._SUB_CATE_SERV_ID;
			}
			set
			{
				if ((this._SUB_CATE_SERV_ID != value))
				{
					this._SUB_CATE_SERV_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATEGORIA_ID", DbType="Int")]
		public System.Nullable<int> SUB_CATEGORIA_ID
		{
			get
			{
				return this._SUB_CATEGORIA_ID;
			}
			set
			{
				if ((this._SUB_CATEGORIA_ID != value))
				{
					this._SUB_CATEGORIA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATEGORIA_NOMBRE", DbType="VarChar(255)")]
		public string SUB_CATEGORIA_NOMBRE
		{
			get
			{
				return this._SUB_CATEGORIA_NOMBRE;
			}
			set
			{
				if ((this._SUB_CATEGORIA_NOMBRE != value))
				{
					this._SUB_CATEGORIA_NOMBRE = value;
				}
			}
		}
	}
	
	public partial class SP_ListarServiciosPorSubCategoriaIdResult
	{
		
		private int _SERVICIO_ID;
		
		private System.Nullable<int> _USUARIO_ID;
		
		private string _USUARIO_NOMBRE;
		
		private string _USUARIO_APELLIDO1;
		
		private string _USUARIO_APELLIDO2;
		
		private System.Nullable<int> _CATEGORIA_ID;
		
		private string _CATEGORIA_NOMBRE;
		
		private string _TITULO;
		
		private string _DESCRIPCION;
		
		private int _PRECIO;
		
		private string _DISPONIBILIDAD;
		
		private System.Nullable<System.DateTime> _CREATED_AT;
		
		private System.Nullable<System.DateTime> _UPDATED_AT;
		
		private System.Nullable<int> _SUB_CATE_SERV_ID;
		
		private System.Nullable<int> _SUB_CATEGORIA_ID;
		
		private string _SUB_CATEGORIA_NOMBRE;
		
		public SP_ListarServiciosPorSubCategoriaIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICIO_ID", DbType="Int NOT NULL")]
		public int SERVICIO_ID
		{
			get
			{
				return this._SERVICIO_ID;
			}
			set
			{
				if ((this._SERVICIO_ID != value))
				{
					this._SERVICIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ID", DbType="Int")]
		public System.Nullable<int> USUARIO_ID
		{
			get
			{
				return this._USUARIO_ID;
			}
			set
			{
				if ((this._USUARIO_ID != value))
				{
					this._USUARIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_NOMBRE", DbType="VarChar(100)")]
		public string USUARIO_NOMBRE
		{
			get
			{
				return this._USUARIO_NOMBRE;
			}
			set
			{
				if ((this._USUARIO_NOMBRE != value))
				{
					this._USUARIO_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_APELLIDO1", DbType="VarChar(100)")]
		public string USUARIO_APELLIDO1
		{
			get
			{
				return this._USUARIO_APELLIDO1;
			}
			set
			{
				if ((this._USUARIO_APELLIDO1 != value))
				{
					this._USUARIO_APELLIDO1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_APELLIDO2", DbType="VarChar(100)")]
		public string USUARIO_APELLIDO2
		{
			get
			{
				return this._USUARIO_APELLIDO2;
			}
			set
			{
				if ((this._USUARIO_APELLIDO2 != value))
				{
					this._USUARIO_APELLIDO2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA_ID", DbType="Int")]
		public System.Nullable<int> CATEGORIA_ID
		{
			get
			{
				return this._CATEGORIA_ID;
			}
			set
			{
				if ((this._CATEGORIA_ID != value))
				{
					this._CATEGORIA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA_NOMBRE", DbType="VarChar(255)")]
		public string CATEGORIA_NOMBRE
		{
			get
			{
				return this._CATEGORIA_NOMBRE;
			}
			set
			{
				if ((this._CATEGORIA_NOMBRE != value))
				{
					this._CATEGORIA_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITULO", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string TITULO
		{
			get
			{
				return this._TITULO;
			}
			set
			{
				if ((this._TITULO != value))
				{
					this._TITULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Int NOT NULL")]
		public int PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISPONIBILIDAD", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DISPONIBILIDAD
		{
			get
			{
				return this._DISPONIBILIDAD;
			}
			set
			{
				if ((this._DISPONIBILIDAD != value))
				{
					this._DISPONIBILIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_AT
		{
			get
			{
				return this._CREATED_AT;
			}
			set
			{
				if ((this._CREATED_AT != value))
				{
					this._CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_AT
		{
			get
			{
				return this._UPDATED_AT;
			}
			set
			{
				if ((this._UPDATED_AT != value))
				{
					this._UPDATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATE_SERV_ID", DbType="Int")]
		public System.Nullable<int> SUB_CATE_SERV_ID
		{
			get
			{
				return this._SUB_CATE_SERV_ID;
			}
			set
			{
				if ((this._SUB_CATE_SERV_ID != value))
				{
					this._SUB_CATE_SERV_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATEGORIA_ID", DbType="Int")]
		public System.Nullable<int> SUB_CATEGORIA_ID
		{
			get
			{
				return this._SUB_CATEGORIA_ID;
			}
			set
			{
				if ((this._SUB_CATEGORIA_ID != value))
				{
					this._SUB_CATEGORIA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATEGORIA_NOMBRE", DbType="VarChar(255)")]
		public string SUB_CATEGORIA_NOMBRE
		{
			get
			{
				return this._SUB_CATEGORIA_NOMBRE;
			}
			set
			{
				if ((this._SUB_CATEGORIA_NOMBRE != value))
				{
					this._SUB_CATEGORIA_NOMBRE = value;
				}
			}
		}
	}
	
	public partial class SP_ListarServiciosPorUsuarioIdResult
	{
		
		private int _SERVICIO_ID;
		
		private System.Nullable<int> _USUARIO_ID;
		
		private string _USUARIO_NOMBRE;
		
		private string _USUARIO_APELLIDO1;
		
		private string _USUARIO_APELLIDO2;
		
		private System.Nullable<int> _CATEGORIA_ID;
		
		private string _CATEGORIA_NOMBRE;
		
		private string _TITULO;
		
		private string _DESCRIPCION;
		
		private int _PRECIO;
		
		private string _DISPONIBILIDAD;
		
		private System.Nullable<System.DateTime> _CREATED_AT;
		
		private System.Nullable<System.DateTime> _UPDATED_AT;
		
		private System.Nullable<int> _SUB_CATE_SERV_ID;
		
		private System.Nullable<int> _SUB_CATEGORIA_ID;
		
		private string _SUB_CATEGORIA_NOMBRE;
		
		public SP_ListarServiciosPorUsuarioIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICIO_ID", DbType="Int NOT NULL")]
		public int SERVICIO_ID
		{
			get
			{
				return this._SERVICIO_ID;
			}
			set
			{
				if ((this._SERVICIO_ID != value))
				{
					this._SERVICIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ID", DbType="Int")]
		public System.Nullable<int> USUARIO_ID
		{
			get
			{
				return this._USUARIO_ID;
			}
			set
			{
				if ((this._USUARIO_ID != value))
				{
					this._USUARIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_NOMBRE", DbType="VarChar(100)")]
		public string USUARIO_NOMBRE
		{
			get
			{
				return this._USUARIO_NOMBRE;
			}
			set
			{
				if ((this._USUARIO_NOMBRE != value))
				{
					this._USUARIO_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_APELLIDO1", DbType="VarChar(100)")]
		public string USUARIO_APELLIDO1
		{
			get
			{
				return this._USUARIO_APELLIDO1;
			}
			set
			{
				if ((this._USUARIO_APELLIDO1 != value))
				{
					this._USUARIO_APELLIDO1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_APELLIDO2", DbType="VarChar(100)")]
		public string USUARIO_APELLIDO2
		{
			get
			{
				return this._USUARIO_APELLIDO2;
			}
			set
			{
				if ((this._USUARIO_APELLIDO2 != value))
				{
					this._USUARIO_APELLIDO2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA_ID", DbType="Int")]
		public System.Nullable<int> CATEGORIA_ID
		{
			get
			{
				return this._CATEGORIA_ID;
			}
			set
			{
				if ((this._CATEGORIA_ID != value))
				{
					this._CATEGORIA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA_NOMBRE", DbType="VarChar(255)")]
		public string CATEGORIA_NOMBRE
		{
			get
			{
				return this._CATEGORIA_NOMBRE;
			}
			set
			{
				if ((this._CATEGORIA_NOMBRE != value))
				{
					this._CATEGORIA_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITULO", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string TITULO
		{
			get
			{
				return this._TITULO;
			}
			set
			{
				if ((this._TITULO != value))
				{
					this._TITULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Int NOT NULL")]
		public int PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISPONIBILIDAD", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DISPONIBILIDAD
		{
			get
			{
				return this._DISPONIBILIDAD;
			}
			set
			{
				if ((this._DISPONIBILIDAD != value))
				{
					this._DISPONIBILIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_AT
		{
			get
			{
				return this._CREATED_AT;
			}
			set
			{
				if ((this._CREATED_AT != value))
				{
					this._CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_AT
		{
			get
			{
				return this._UPDATED_AT;
			}
			set
			{
				if ((this._UPDATED_AT != value))
				{
					this._UPDATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATE_SERV_ID", DbType="Int")]
		public System.Nullable<int> SUB_CATE_SERV_ID
		{
			get
			{
				return this._SUB_CATE_SERV_ID;
			}
			set
			{
				if ((this._SUB_CATE_SERV_ID != value))
				{
					this._SUB_CATE_SERV_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATEGORIA_ID", DbType="Int")]
		public System.Nullable<int> SUB_CATEGORIA_ID
		{
			get
			{
				return this._SUB_CATEGORIA_ID;
			}
			set
			{
				if ((this._SUB_CATEGORIA_ID != value))
				{
					this._SUB_CATEGORIA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATEGORIA_NOMBRE", DbType="VarChar(255)")]
		public string SUB_CATEGORIA_NOMBRE
		{
			get
			{
				return this._SUB_CATEGORIA_NOMBRE;
			}
			set
			{
				if ((this._SUB_CATEGORIA_NOMBRE != value))
				{
					this._SUB_CATEGORIA_NOMBRE = value;
				}
			}
		}
	}
	
	public partial class SP_ListarSubCategoriasResult
	{
		
		private int _SUB_CATEGORIA_ID;
		
		private string _NOMBRE;
		
		private string _CATEGORIA;
		
		public SP_ListarSubCategoriasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATEGORIA_ID", DbType="Int NOT NULL")]
		public int SUB_CATEGORIA_ID
		{
			get
			{
				return this._SUB_CATEGORIA_ID;
			}
			set
			{
				if ((this._SUB_CATEGORIA_ID != value))
				{
					this._SUB_CATEGORIA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA", DbType="VarChar(255)")]
		public string CATEGORIA
		{
			get
			{
				return this._CATEGORIA;
			}
			set
			{
				if ((this._CATEGORIA != value))
				{
					this._CATEGORIA = value;
				}
			}
		}
	}
	
	public partial class SP_ObtenerServicioResult
	{
		
		private int _SERVICIO_ID;
		
		private System.Nullable<int> _USUARIO_ID;
		
		private string _USUARIO_NOMBRE;
		
		private string _USUARIO_APELLIDO1;
		
		private string _USUARIO_APELLIDO2;
		
		private System.Nullable<int> _CATEGORIA_ID;
		
		private string _CATEGORIA_NOMBRE;
		
		private string _TITULO;
		
		private string _DESCRIPCION;
		
		private int _PRECIO;
		
		private string _DISPONIBILIDAD;
		
		private System.Nullable<System.DateTime> _CREATED_AT;
		
		private System.Nullable<System.DateTime> _UPDATED_AT;
		
		private System.Nullable<int> _SUB_CATE_SERV_ID;
		
		private System.Nullable<int> _SUB_CATEGORIA_ID;
		
		private string _SUB_CATEGORIA_NOMBRE;
		
		public SP_ObtenerServicioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERVICIO_ID", DbType="Int NOT NULL")]
		public int SERVICIO_ID
		{
			get
			{
				return this._SERVICIO_ID;
			}
			set
			{
				if ((this._SERVICIO_ID != value))
				{
					this._SERVICIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ID", DbType="Int")]
		public System.Nullable<int> USUARIO_ID
		{
			get
			{
				return this._USUARIO_ID;
			}
			set
			{
				if ((this._USUARIO_ID != value))
				{
					this._USUARIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_NOMBRE", DbType="VarChar(100)")]
		public string USUARIO_NOMBRE
		{
			get
			{
				return this._USUARIO_NOMBRE;
			}
			set
			{
				if ((this._USUARIO_NOMBRE != value))
				{
					this._USUARIO_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_APELLIDO1", DbType="VarChar(100)")]
		public string USUARIO_APELLIDO1
		{
			get
			{
				return this._USUARIO_APELLIDO1;
			}
			set
			{
				if ((this._USUARIO_APELLIDO1 != value))
				{
					this._USUARIO_APELLIDO1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_APELLIDO2", DbType="VarChar(100)")]
		public string USUARIO_APELLIDO2
		{
			get
			{
				return this._USUARIO_APELLIDO2;
			}
			set
			{
				if ((this._USUARIO_APELLIDO2 != value))
				{
					this._USUARIO_APELLIDO2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA_ID", DbType="Int")]
		public System.Nullable<int> CATEGORIA_ID
		{
			get
			{
				return this._CATEGORIA_ID;
			}
			set
			{
				if ((this._CATEGORIA_ID != value))
				{
					this._CATEGORIA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATEGORIA_NOMBRE", DbType="VarChar(255)")]
		public string CATEGORIA_NOMBRE
		{
			get
			{
				return this._CATEGORIA_NOMBRE;
			}
			set
			{
				if ((this._CATEGORIA_NOMBRE != value))
				{
					this._CATEGORIA_NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITULO", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string TITULO
		{
			get
			{
				return this._TITULO;
			}
			set
			{
				if ((this._TITULO != value))
				{
					this._TITULO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DESCRIPCION", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DESCRIPCION
		{
			get
			{
				return this._DESCRIPCION;
			}
			set
			{
				if ((this._DESCRIPCION != value))
				{
					this._DESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRECIO", DbType="Int NOT NULL")]
		public int PRECIO
		{
			get
			{
				return this._PRECIO;
			}
			set
			{
				if ((this._PRECIO != value))
				{
					this._PRECIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISPONIBILIDAD", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DISPONIBILIDAD
		{
			get
			{
				return this._DISPONIBILIDAD;
			}
			set
			{
				if ((this._DISPONIBILIDAD != value))
				{
					this._DISPONIBILIDAD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> CREATED_AT
		{
			get
			{
				return this._CREATED_AT;
			}
			set
			{
				if ((this._CREATED_AT != value))
				{
					this._CREATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPDATED_AT", DbType="DateTime")]
		public System.Nullable<System.DateTime> UPDATED_AT
		{
			get
			{
				return this._UPDATED_AT;
			}
			set
			{
				if ((this._UPDATED_AT != value))
				{
					this._UPDATED_AT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATE_SERV_ID", DbType="Int")]
		public System.Nullable<int> SUB_CATE_SERV_ID
		{
			get
			{
				return this._SUB_CATE_SERV_ID;
			}
			set
			{
				if ((this._SUB_CATE_SERV_ID != value))
				{
					this._SUB_CATE_SERV_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATEGORIA_ID", DbType="Int")]
		public System.Nullable<int> SUB_CATEGORIA_ID
		{
			get
			{
				return this._SUB_CATEGORIA_ID;
			}
			set
			{
				if ((this._SUB_CATEGORIA_ID != value))
				{
					this._SUB_CATEGORIA_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUB_CATEGORIA_NOMBRE", DbType="VarChar(255)")]
		public string SUB_CATEGORIA_NOMBRE
		{
			get
			{
				return this._SUB_CATEGORIA_NOMBRE;
			}
			set
			{
				if ((this._SUB_CATEGORIA_NOMBRE != value))
				{
					this._SUB_CATEGORIA_NOMBRE = value;
				}
			}
		}
	}
	
	public partial class SP_ObtenerUsuarioResult
	{
		
		private int _USUARIO_ID;
		
		private string _NOMBRE;
		
		private string _APELLIDO1;
		
		private string _APELLIDO2;
		
		private System.DateTime _FECHA_NACIMIENTO;
		
		private string _CORREO;
		
		private string _FOTO_PERFIL;
		
		private string _TELEFONO;
		
		private string _DIRECCION;
		
		private System.Nullable<int> _VERIFICACION;
		
		private bool _PERFIL_COMPLETO;
		
		private bool _ACTIVO;
		
		private string _PROVINCIA;
		
		private string _CANTON;
		
		public SP_ObtenerUsuarioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USUARIO_ID", DbType="Int NOT NULL")]
		public int USUARIO_ID
		{
			get
			{
				return this._USUARIO_ID;
			}
			set
			{
				if ((this._USUARIO_ID != value))
				{
					this._USUARIO_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NOMBRE
		{
			get
			{
				return this._NOMBRE;
			}
			set
			{
				if ((this._NOMBRE != value))
				{
					this._NOMBRE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO1", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string APELLIDO1
		{
			get
			{
				return this._APELLIDO1;
			}
			set
			{
				if ((this._APELLIDO1 != value))
				{
					this._APELLIDO1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO2", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string APELLIDO2
		{
			get
			{
				return this._APELLIDO2;
			}
			set
			{
				if ((this._APELLIDO2 != value))
				{
					this._APELLIDO2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_NACIMIENTO", DbType="Date NOT NULL")]
		public System.DateTime FECHA_NACIMIENTO
		{
			get
			{
				return this._FECHA_NACIMIENTO;
			}
			set
			{
				if ((this._FECHA_NACIMIENTO != value))
				{
					this._FECHA_NACIMIENTO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CORREO", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string CORREO
		{
			get
			{
				return this._CORREO;
			}
			set
			{
				if ((this._CORREO != value))
				{
					this._CORREO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FOTO_PERFIL", DbType="VarChar(255)")]
		public string FOTO_PERFIL
		{
			get
			{
				return this._FOTO_PERFIL;
			}
			set
			{
				if ((this._FOTO_PERFIL != value))
				{
					this._FOTO_PERFIL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO", DbType="VarChar(20)")]
		public string TELEFONO
		{
			get
			{
				return this._TELEFONO;
			}
			set
			{
				if ((this._TELEFONO != value))
				{
					this._TELEFONO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string DIRECCION
		{
			get
			{
				return this._DIRECCION;
			}
			set
			{
				if ((this._DIRECCION != value))
				{
					this._DIRECCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERIFICACION", DbType="Int")]
		public System.Nullable<int> VERIFICACION
		{
			get
			{
				return this._VERIFICACION;
			}
			set
			{
				if ((this._VERIFICACION != value))
				{
					this._VERIFICACION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERFIL_COMPLETO", DbType="Bit NOT NULL")]
		public bool PERFIL_COMPLETO
		{
			get
			{
				return this._PERFIL_COMPLETO;
			}
			set
			{
				if ((this._PERFIL_COMPLETO != value))
				{
					this._PERFIL_COMPLETO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACTIVO", DbType="Bit NOT NULL")]
		public bool ACTIVO
		{
			get
			{
				return this._ACTIVO;
			}
			set
			{
				if ((this._ACTIVO != value))
				{
					this._ACTIVO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROVINCIA", DbType="VarChar(255)")]
		public string PROVINCIA
		{
			get
			{
				return this._PROVINCIA;
			}
			set
			{
				if ((this._PROVINCIA != value))
				{
					this._PROVINCIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CANTON", DbType="VarChar(255)")]
		public string CANTON
		{
			get
			{
				return this._CANTON;
			}
			set
			{
				if ((this._CANTON != value))
				{
					this._CANTON = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
